spring:
  application:
    name: api
  profiles:
    active: develop
  jpa:
    open-in-view: false
    mapping-resources:
    - namedNativeQuery/query.xml
server:
  port: 13713
  servlet:
    context-path: /ajp-api
    encoding:
      charset: utf-8
      enabled: true
      force: true
springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: / #swagger redirect /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    display-operation-id: true
    filter: true
security:
  jwt:
    secret-key: ${jwt-key}
    issuer: aljjabaegi.tistory.com
  jasypt:
    secret-key: ${jasypt-key}
  rsa:
    algorithm: RSA
    key-size: 2048
    private: ${rsa-private} #config/security/rsa/RsaProvider 참고
    public: ${rsa-public}

--- #develop

spring:
  config:
    activate:
      on-profile: develop
  datasource:
    #    url: "jdbc:mariadb://{ip}:{port}/{schema}" #mariadb
    #    driver-class-name: "org.mariadb.jdbc.Driver" #mariadb
    url: "jdbc:postgresql://localhost:15432/test_db"
    driver-class-name: "org.postgresql.Driver"
    username: aljjabaegi
    password: ENC(xLC9ZsqaoOZJ/udaUpOeYOrqdTFsMS+O4JZ483N7AUM=)
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create